# Generated by Django 5.0.4 on 2024-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='src',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/user_avatars/', verbose_name='Ссылка'),
        ),
    ]
