# Generated by Django 5.0.4 on 2024-06-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_name', models.CharField(max_length=80)),
                ('card_month', models.CharField(max_length=3)),
                ('card_year', models.CharField(max_length=3)),
                ('card_cvv_code', models.CharField(max_length=3)),
                ('payment_status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='order.order')),
            ],
        ),
    ]
