# Generated by Django 5.0.4 on 2024-04-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
