# Generated by Django 5.0.4 on 2024-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, default='image', max_length=200),
        ),
    ]
