# Generated by Django 5.0.4 on 2024-05-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_sale', models.BooleanField(default=False)),
                ('salePrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('dateFrom', models.DateTimeField(blank=True, null=True)),
                ('deteTo', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSale', to='product.product')),
            ],
        ),
    ]
