# Generated by Django 5.0.4 on 2024-05-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
        ('product', '0006_productsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('deliveryType', models.CharField(choices=[('delivery_free', 'Обычная бесплатная доставка'), ('pickup', 'Экспресс доставка')], default='Обычная доставка', max_length=80)),
                ('paymentType', models.CharField(choices=[('online', 'Онлайн картой'), ('оффлайн', 'Онлайн с чужой карты')], default='Онлайн картой', max_length=30)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(default='in process', max_length=200)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('basket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='basket.basket')),
                ('products', models.ManyToManyField(related_name='orders', to='product.product')),
            ],
        ),
    ]
